# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import placar_pb2 as placar__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in placar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlacarStub:
    """Contrato entre o serviço de visão computacional (Python) e a API (Rust).

    Este arquivo fica na raiz do repositório, e não dentro de backend/ ou ia/,
    porque não pertence a nenhum dos dois: é o acordo entre eles. As duas
    linguagens geram código a partir daqui, então mudar uma mensagem quebra
    os dois lados — o que é justamente a intenção de um contrato explícito.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarEvento = channel.unary_unary(
                '/placar.Placar/RegistrarEvento',
                request_serializer=placar__pb2.EventoDetectado.SerializeToString,
                response_deserializer=placar__pb2.EventoRegistrado.FromString,
                _registered_method=True)
        self.RegistrarEventos = channel.stream_unary(
                '/placar.Placar/RegistrarEventos',
                request_serializer=placar__pb2.EventoDetectado.SerializeToString,
                response_deserializer=placar__pb2.ResumoRegistro.FromString,
                _registered_method=True)


class PlacarServicer:
    """Contrato entre o serviço de visão computacional (Python) e a API (Rust).

    Este arquivo fica na raiz do repositório, e não dentro de backend/ ou ia/,
    porque não pertence a nenhum dos dois: é o acordo entre eles. As duas
    linguagens geram código a partir daqui, então mudar uma mensagem quebra
    os dois lados — o que é justamente a intenção de um contrato explícito.

    """

    def RegistrarEvento(self, request, context):
        """Registra um único evento detectado. Use quando a detecção é pontual.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarEventos(self, request_iterator, context):
        """Fluxo contínuo: a IA envia eventos conforme processa o vídeo, sem
        esperar resposta a cada um, e recebe um resumo quando o fluxo termina.
        É aqui que o gRPC se paga em relação a um POST por evento — uma única
        conexão HTTP/2 carrega todos eles.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlacarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarEvento,
                    request_deserializer=placar__pb2.EventoDetectado.FromString,
                    response_serializer=placar__pb2.EventoRegistrado.SerializeToString,
            ),
            'RegistrarEventos': grpc.stream_unary_rpc_method_handler(
                    servicer.RegistrarEventos,
                    request_deserializer=placar__pb2.EventoDetectado.FromString,
                    response_serializer=placar__pb2.ResumoRegistro.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'placar.Placar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('placar.Placar', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Placar:
    """Contrato entre o serviço de visão computacional (Python) e a API (Rust).

    Este arquivo fica na raiz do repositório, e não dentro de backend/ ou ia/,
    porque não pertence a nenhum dos dois: é o acordo entre eles. As duas
    linguagens geram código a partir daqui, então mudar uma mensagem quebra
    os dois lados — o que é justamente a intenção de um contrato explícito.

    """

    @staticmethod
    def RegistrarEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/placar.Placar/RegistrarEvento',
            placar__pb2.EventoDetectado.SerializeToString,
            placar__pb2.EventoRegistrado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarEventos(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/placar.Placar/RegistrarEventos',
            placar__pb2.EventoDetectado.SerializeToString,
            placar__pb2.ResumoRegistro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
