# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: placar.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'placar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplacar.proto\x12\x06placar\"\x8b\x01\n\x0f\x45ventoDetectado\x12\x12\n\npartida_id\x18\x01 \x01(\x05\x12\x12\n\njogador_id\x18\x02 \x01(\x05\x12 \n\x04tipo\x18\x03 \x01(\x0e\x32\x12.placar.TipoEvento\x12\x1b\n\x0etempo_video_ms\x18\x04 \x01(\x05H\x00\x88\x01\x01\x42\x11\n\x0f_tempo_video_ms\".\n\x10\x45ventoRegistrado\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06pontos\x18\x02 \x01(\x05\"D\n\x0eResumoRegistro\x12\x1b\n\x13\x65ventos_registrados\x18\x01 \x01(\x05\x12\x15\n\rpontos_totais\x18\x02 \x01(\x05*d\n\nTipoEvento\x12 \n\x1cTIPO_EVENTO_NAO_ESPECIFICADO\x10\x00\x12\x0b\n\x07\x43\x45STA_2\x10\x01\x12\x0b\n\x07\x43\x45STA_3\x10\x02\x12\x0f\n\x0bLANCE_LIVRE\x10\x03\x12\t\n\x05\x46\x41LTA\x10\x04\x32\x95\x01\n\x06Placar\x12\x44\n\x0fRegistrarEvento\x12\x17.placar.EventoDetectado\x1a\x18.placar.EventoRegistrado\x12\x45\n\x10RegistrarEventos\x12\x17.placar.EventoDetectado\x1a\x16.placar.ResumoRegistro(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'placar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIPOEVENTO']._serialized_start=284
  _globals['_TIPOEVENTO']._serialized_end=384
  _globals['_EVENTODETECTADO']._serialized_start=25
  _globals['_EVENTODETECTADO']._serialized_end=164
  _globals['_EVENTOREGISTRADO']._serialized_start=166
  _globals['_EVENTOREGISTRADO']._serialized_end=212
  _globals['_RESUMOREGISTRO']._serialized_start=214
  _globals['_RESUMOREGISTRO']._serialized_end=282
  _globals['_PLACAR']._serialized_start=387
  _globals['_PLACAR']._serialized_end=536
# @@protoc_insertion_point(module_scope)
